### ISSUE TITLE
Ecto subqueries leads to missing select clause

### ISSUE THREAD

**Issue by sck-v** [appodeal/clickhouse_ecto#4]
Hey! 🖖

I have following ecto query:

```
 views = View |> select([v], %{offset: v.offset})
```
It generates valid sql `SELECT s0."offset" FROM "views"`

When i'm trying to use it as subquery, for example:
```
from v in subquery(views), select: v.offset
```
then the resulting SQL looks somehow wrong:

`SELECT s0."offset" FROM (SELECT 'TRUE' FROM "views" AS s0) AS s0 []`

After some investigation i've found that problem is likely here
https://github.com/appodeal/clickhouse_ecto/blob/master/lib/clickhouse_ecto/query_string.ex#L202
because of `views.fields` field is nil after building initial query.

**Comment by santaux** [comment]
Hi @sck-v ,
Sorry for late answer. This bug was fixed in version 0.2.4. Please, check it out: https://github.com/appodeal/clickhouse_ecto/pull/6/commits/d850d04ad8ce8738d7695f4b169a3ca636c3e819

Does it work for you? Can I close the issue?

**Comment by santaux** [comment]
At least your example works in out example app:

```
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> import Ecto.Query
Ecto.Query
iex(2)> ExampleApp.Repo.all ExampleApp.Click                     
[debug] QUERY OK source="clicks" db=2.9ms
SELECT c0."date", c0."site_id", c0."source", c0."ip", c0."score", c0."width", c0."height", c0."inserted_at" FROM "clicks" AS c0 []
[]
iex(3)> query1 = ExampleApp.Click |> select([c], %{ip: c.ip})
#Ecto.Query<from c in ExampleApp.Click, select: %{ip: c.ip}>
iex(4)> from c in subquery(query1), select: c.ip
#Ecto.Query<from c in subquery(from c in ExampleApp.Click,
  select: %{ip: c.ip}),
 select: c.ip>
iex(5)> ExampleApp.Repo.all from c in subquery(query1), select: c.ip
[debug] QUERY OK db=2.5ms
SELECT s0."ip" FROM (SELECT c0."ip" AS "ip" FROM "clicks" AS c0) AS s0 []
[]
iex(6)>
```

**Comment by sck-v** [comment]
Hey, @santaux 

Seems like everything is fine :)
Thanks for update

Closing the issue
