### ISSUE TITLE
WITH TOTALS dont work

### ISSUE THREAD

**Issue by ivan-safonov** [appodeal/clickhouse_ecto#5]
Hey

I have such group_by in my query: 
`group_by(query, [s], fragment("?, ? WITH TOTALS", s.param, s.param2))`
query is correct and it works, but WITH TOTALS add key "totals" in result map which is not handled by clickhousex I guess and query return results without totals at all.

It will be great if you can fix it, thanks.

**Comment by santaux** [comment]
Hi @ivan-safonov

Sorry, I can't do it right now. May be you can fix it by yourself and provide the PR?
